### ISSUE TITLE
음악 재생이 안돼요..

### ISSUE THREAD

**Issue by gurumi0301** [whguswo/discord-musicbot#3]
아직도 보실 진 모르겠지만, 봐주신다면 친절한 답변 부탁드립니다!

discord.js v14에서 해보고 싶어서 모듈과 ffmpeg를 설치하고 코드를 붙여넣기 해서 했습니당.
커맨드 핸들러를 통해 사용하고 있기 때문에 각 코드에 있는 파일 경로 등을 수정하고, 
index.js에 있던 커맨드 핸들 부분과 등록 부분을 제외한 나머지는 제대로 했습니당.

ffmpeg도 설치해서 path였나 수정해서, cmd에서 ffmpeg -version을 사용했을 때 제대로 내용이 나오는 것 까지 확인했습니당.
찾아보니 cmd로 환경 변수 설정? 같은 걸 해야한다고 해서 그거 따라서 했어요..

유튜브 API를 확인해보면 사용 기록이 있는 걸 봐서 API는 정상적으로 동작하는 듯 해요..

문제는,

1. 음성 채널에 들어와 있지 않은데 봇이 혼자서 음성 채널에 들어가요..
    정확하진 않지만 커맨드를 공용으로 등록해서 그럴 지도 모르겠네요오..

2. play를 사용하면 다른 건 정상적으로 동작하지만, 음악이 재생되지 않아요!
    ffmpeg도 확인했고, 딱히 오류가 발생했다고는 안 뜨는데.. 재생이 안되네요..
    
3. 재생이 안 되는데 그에 관한 오류가 안 떠요!
    당연하지만 코드 오류가 아니라서 그러겠죠..?
    interactionCreate를 이용해 오류를 찾도록 하는 시스템까지 있는데도 오류가 없다고 하네요.
    whguswo님께서 만드신 부분에서 발생하는 오류는 아닌 거 같네요..
    
현재로서 보이는 문제는 이 정도입니당.. 
필요하신 부분 있으시면 코드 올려드릴께요!

package.json:

"dependencies": {
    "@discordjs/opus": "^0.9.0",
    "@discordjs/rest": "^2.2.0",
    "@discordjs/voice": "^0.16.1",
    "discord.js": "^14.14.1",
    "dotenv": "^16.4.5",
    "googleapis": "^133.0.0",
    "iso8601-duration": "^2.1.2",
    "libsodium-wrappers": "^0.7.13",
    "ytdl-core": "^4.11.5"
  }

**Comment by gurumi0301** [comment]
파일 경로는
src
-commands
  |-music
     |-pause, play, stop 등 js파일

-events
  |-client
     |-catchError.js (interactionCreate 이벤트를 이용한 일종의 에러 핸들러랄까..? )

-functions
  |-handlers
     |-commandhandle, eventhandle 등 js 파일

-bot.js (index.js와 동일 파일, 커맨드 등록 부분은 제외했어요..! 여기에 module.exports = { queue, log }; 가 있어요! )
-manageQueue.js

대부분의 파일은 파일 경로를 제외한 나머지 부분을 수정하지 않았어요..!

**Comment by gurumi0301** [comment]
열심히 코드를 읽어서 대충 원리는 파악 했지만.. 그래도 정확하진 않네요..

혹시 괜찮으시다면 원리까지 자세히 설명해주시면 정말 감사하겠습니다!

**Comment by whguswo** [comment]
옛날에 대충만든거라 언젠가 수정해서 올리고 그래도 오류가 발생하면 도와드리겠습니다.

**Comment by gurumi0301** [comment]
지금은 어찌저찌 했어요!
어쨌든 늦었음에도 봐주셔서 감사합니당!
애써 해주실 필요는 없어용
